-- MySQL Script generated by MySQL Workbench
-- 06/26/17 15:48:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetJava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetJava` DEFAULT CHARACTER SET utf8 ;
USE `projetJava` ;

-- -----------------------------------------------------
-- Table `projetJava`.`Specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Specialite` (
  `idSpecialite` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `code` CHAR(3) NOT NULL,
  PRIMARY KEY (`idSpecialite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Objectif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Objectif` (
  `idObjectif` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idObjectif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Formation` (
  `idFormation` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `fk_specialite` INT NOT NULL,
  `fk_objectif` INT NOT NULL,
  PRIMARY KEY (`idFormation`, `fk_objectif`),
  INDEX `fk_specialte_idx` (`fk_specialite` ASC),
  INDEX `fk_Formation_Objectif1_idx` (`fk_objectif` ASC),
  CONSTRAINT `fk_specialte`
    FOREIGN KEY (`fk_specialite`)
    REFERENCES `projetJava`.`Specialite` (`idSpecialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_Objectif1`
    FOREIGN KEY (`fk_objectif`)
    REFERENCES `projetJava`.`Objectif` (`idObjectif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Stagiaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Stagiaire` (
  `idStagiaire` INT NOT NULL,
  `interne` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idStagiaire`),
  INDEX `fk_personneStagiaire_idx` (`idStagiaire` ASC),
  CONSTRAINT `fk_personneStagiaire`
    FOREIGN KEY (`idStagiaire`)
    REFERENCES `projetJava`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Formateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Formateur` (
  `idFormateur` INT NOT NULL,
  `interne` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idFormateur`),
  INDEX `fk_personneFormateur_idx` (`idFormateur` ASC),
  CONSTRAINT `fk_personneFormateur`
    FOREIGN KEY (`idFormateur`)
    REFERENCES `projetJava`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Financement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Financement` (
  `idFinancement` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFinancement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`FinancementStagiaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`FinancementStagiaire` (
  `fk_stagiaire` INT NOT NULL,
  `fk_financement` INT NOT NULL,
  `dateDebut` DATE NOT NULL,
  `dateFin` DATE,
  INDEX `fk_stagiaireFS_idx` (`fk_stagiaire` ASC),
  INDEX `fk_financementFS_idx` (`fk_financement` ASC),
  PRIMARY KEY (`dateDebut`, `fk_stagiaire`, `fk_financement`),
  CONSTRAINT `fk_stagiaireFS`
    FOREIGN KEY (`fk_stagiaire`)
    REFERENCES `projetJava`.`Stagiaire` (`idStagiaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financementFS`
    FOREIGN KEY (`fk_financement`)
    REFERENCES `projetJava`.`Financement` (`idFinancement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`Creneau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`Creneau` (
  `idCreneau` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `interne` TINYINT(1) NOT NULL,
  `fk_formation` INT NOT NULL,
  PRIMARY KEY (`idCreneau`),
  INDEX `fk_formationCreneau_idx` (`fk_formation` ASC),
  CONSTRAINT `fk_formationCreneau`
    FOREIGN KEY (`fk_formation`)
    REFERENCES `projetJava`.`Formation` (`idFormation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`CreneauStagiaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`CreneauStagiaire` (
  `fk_stagiaire` INT NOT NULL,
  `fk_creneau` INT NOT NULL,
  INDEX `fk_stagiaireCS_idx` (`fk_stagiaire` ASC),
  INDEX `fk_creneauCS_idx` (`fk_creneau` ASC),
  PRIMARY KEY (`fk_stagiaire`, `fk_creneau`),
  CONSTRAINT `fk_stagiaireCS`
    FOREIGN KEY (`fk_stagiaire`)
    REFERENCES `projetJava`.`Stagiaire` (`idStagiaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_creneauCS`
    FOREIGN KEY (`fk_creneau`)
    REFERENCES `projetJava`.`Creneau` (`idCreneau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetJava`.`CreneauFormateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetJava`.`CreneauFormateur` (
  `fk_formateur` INT NOT NULL,
  `fk_creneau` INT NOT NULL,
  INDEX `fk_formateurCF_idx` (`fk_formateur` ASC),
  INDEX `fk_creneauCF_idx` (`fk_creneau` ASC),
  PRIMARY KEY (`fk_formateur`, `fk_creneau`),
  CONSTRAINT `fk_formateurCreneauF`
    FOREIGN KEY (`fk_formateur`)
    REFERENCES `projetJava`.`Formateur` (`idFormateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_creneauCreneauF`
    FOREIGN KEY (`fk_creneau`)
    REFERENCES `projetJava`.`Creneau` (`idCreneau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
